Fix include path for ./parsers
It was caused by https://github.com/jacketizer/libnmea/pull/46.
Since src/parsers directory wasn't in include path,
it leads to the following error while compiling libnmea:
src/parsers/gpgga.h:7:10: fatal error: nmea.h: No such file or directory
    7 | #include <nmea.h>